### ISSUE TITLE
I have the same key position as you, can I directly apply it without modifying the configuration? Then I would like to know how the special features in this cfg file are implemented.

### ISSUE THREAD

**Issue by haohaoya12** [mija/mija.cfg#1]

**Comment by haohaoya12** [comment]
Because I found many functions marked inside, I don't know how to change the buttons

**Comment by mija** [comment]
everything is stored in aliases in the mija.cfg file.
binds will always have the word "bind" before it so you can search for "bind" in the file and change the key that follows.

i see that your other messages are in repos about deadlock cheats. this is not a cheat. this is a settings file.

**Comment by haohaoya12** [comment]
I know, cheating is just learning the function of testing, understanding can quickly identify whether the other party has a problem. haha

I just hope this helps, like a lot of buttons, you use aliases, it looks like I'm already dizzy. For example, quick spells and quick items, such as special hero Settings, do not know how to press
